[package]
name = "new-game-tokio-drift"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
dioxus = "0.4.0"
dioxus-tui = "0.4.0"
rand = "0.8.5"
tui = "0.19.0"
